<a href="https://colab.research.google.com/github/jagadish432/mlzoomcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
np.array([1,2,3,4,7,9,11])

array([ 1,  2,  3,  4,  7,  9, 11])

In [ ]:
a = np.array([1,2,3,4,7,9,11])
a

array([ 1,  2,  3,  4,  7,  9, 11])

In [ ]:
a[3]

4

In [ ]:
len(a)

7

In [ ]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 3)
# didn't generate numbers because start should be < end number

array([], dtype=int64)

In [ ]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [ ]:
# generates number of values(based on 3rd param) between the 1st
# and 2nd numbers
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(0, 80, 9)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80.])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
mat[1]
mat[2][0]

7

In [ ]:
len(mat)
len(mat[2])


3

In [ ]:
mat[2][0] = 200
mat

array([[  1,   2,   3],
       [  4,   5,   6],
       [200,   8,   9],
       [ 10,  11,  12]])

In [ ]:
mat[2] = [0,1,2]
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  1,  2],
       [10, 11, 12]])

In [ ]:
# not enough values here as we have 4 rows but have given 3 rows' values for the last column
mat[:, 2] = [0,1,2]

ValueError: could not broadcast input array from shape (3,) into shape (4,)

In [ ]:
mat[0, 2] = 999
mat


array([[  1,   2, 999],
       [  4,   5,   6],
       [  0,   1,   2],
       [ 10,  11,  12]])

In [ ]:
mat[:, 2] = [0,1,2,3]
mat

array([[ 1,  2,  0],
       [ 4,  5,  1],
       [ 0,  1,  2],
       [10, 11,  3]])

In [ ]:
mat[1, :] = [7,8,9]
mat

array([[ 1,  2,  0],
       [ 7,  8,  9],
       [ 0,  1,  2],
       [10, 11,  3]])

In [ ]:
np.random.rand(5,2)

array([[0.45517093, 0.10070959],
       [0.24037644, 0.9460672 ],
       [0.98182297, 0.05944606],
       [0.87985472, 0.99597057],
       [0.05300417, 0.36153055]])

In [ ]:
# fixing seed i.e., same result on any computer when run any number of times
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 1

array([1, 2, 3, 4, 5])

In [ ]:
a * 6
# normal python list wouldn't support this, numpy does :)

array([ 0,  6, 12, 18, 24])

In [ ]:
a // 3

array([0, 0, 0, 1, 1])

In [ ]:
a % 3

array([0, 1, 2, 0, 1])

In [ ]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
a
b
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [ ]:
a > b

array([False, False,  True,  True,  True])

In [ ]:
a[a>b]

array([2, 3, 4])

In [ ]:
b[b<a]

array([1.96, 2.56, 3.24])

In [ ]:
b[b>a]

array([1.  , 1.44])

In [ ]:
b.max()

3.24

In [ ]:
b.sum()

10.200000000000001

In [ ]:
b.mean()

2.04

In [ ]:
b.std()

0.7947829892492667

In [ ]:
mat

array([[ 1,  2,  0],
       [ 7,  8,  9],
       [ 0,  1,  2],
       [10, 11,  3]])

In [ ]:
mat.sum()

54

In [ ]:
mat.mean()

4.5

In [ ]:
mat.std()

3.9895697345286076

In [6]:
def vector_vector_multiplication(u, v):
  assert u.shape[0] == v.shape[0]

  n = u.shape[0]
  # v = u.shape[0]
  result = 0

  for i in range(n):
    result += u[i] * v[i]
  return result

In [7]:
u = np.array([0,1,2,3])
v = np.array([4,5,6,7])

In [9]:
print(vector_vector_multiplication(u, v))

# numpy builtin function
u.dot(v)

38


38

In [10]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

v = np.array([1, 0.5, 2, 1])

In [13]:
# Matrix-Vector multiplication
U.dot(v)

array([20. ,  6. ,  8.5])

In [14]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])


In [15]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [16]:
# generate a identity matrix  - 1's on diagonal and 0's at other places

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Inverse

V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [19]:
V[[0,1,2]]

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [22]:
# forming square matrix 3X3
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [24]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [25]:
Vs.dot(Vs_inv) # Mat X Mat_Inverse yeilds identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])